
export const SET_BLOG_LOADING = 'SET_BLOG_LOADING';
export const SET_BLOG_ERROR = 'SET_BLOG_ERROR';
export const SET_BLOG = 'SET_BLOG';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const REMOVE_SINGLE_BLOG = 'REMOVE_SINGLE_BLOG';